<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SAT-DUL-RUSSELL" name="bst.cpo.automation.dm.tests.Demo" tests="8" failures="0" timestamp="22 Jun 2015 17:29:53 GMT" time="143.741" errors="1">
  <testcase name="Help_File" time="22.118" classname="bst.cpo.automation.dm.tests.Demo"/>
  <testcase name="Add_File" time="24.088" classname="bst.cpo.automation.dm.tests.Demo"/>
  <testcase name="Add_File_Note" time="30.650" classname="bst.cpo.automation.dm.tests.Demo"/>
  <testcase name="Select_File_Copy" time="12.978" classname="bst.cpo.automation.dm.tests.Demo"/>
  <testcase name="Login_User" time="21.853" classname="bst.cpo.automation.dm.tests.Demo"/>
  <testcase name="Delete_File_Cancel" time="6.130" classname="bst.cpo.automation.dm.tests.Demo"/>
  <testcase name="Settings_Admin_Fail" time="5.514" classname="bst.cpo.automation.dm.tests.Demo">
    <error type="java.lang.AssertionError" message="Failed - Navigation to &#039;Admin Center&#039; expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Failed - Navigation to 'Admin Center' expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at bst.cpo.automation.dm.actions.Home_Actions.Nav_Settings_Click(Home_Actions.java:107)
	at bst.cpo.automation.dm.tests.Demo.Settings_Admin_Fail(Demo.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- Settings_Admin_Fail -->
  <testcase name="User_Search" time="20.410" classname="bst.cpo.automation.dm.tests.Demo"/>
</testsuite> <!-- bst.cpo.automation.dm.tests.Demo -->
